# Generated by Django 3.2.4 on 2021-06-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.FloatField()),
                ('age_rating', models.CharField(max_length=100)),
                ('imdb_rating', models.FloatField()),
                ('on_netflix', models.IntegerField()),
            ],
        ),
    ]
